accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from .forms import CustomAuthenticationForm



#from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #url(r'^entrar/$', 'django.contrib.auth.views.login',         {'template_name': 'accounts/login.html'}, name='login'),
    #url(r'^sair/$', 'django.contrib.auth.views.logout',            {'next_page': 'core:home'}, name='logout'),
    url(r'^cadastre-se/$', accounts_views.register,         name='register'),
    url(r'^entrar/$', auth_views.LoginView.as_view(template_name = 'accounts/login.html',
          authentication_form = CustomAuthenticationForm),        name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^password/$', accounts_views.change_password, name='change_password'),


    url(r'^profile/lista/$', accounts_views.ProfileListView.as_view(), name='profile_list'),
    url(r'^profile/add/$', accounts_views.add_profile, name='profile_add'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', accounts_views.update_profile, name='profile_update'),
    url(r'^profile/(?P<pk>[0-9]+)/delete/$', accounts_views.delete_profile, name='profile_delete'),
    url(r'^profile/$', accounts_views.ProfileView.as_view(), name='profile'),

    url(r'^password_change/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'),
    url(r'^password_reset/$', accounts_views.UserPasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),



]

polls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
]

portal/tools/server/src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve', { 'insecure': True }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
) + i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^checklists/', include('checklist.urls', namespace='Checklists')),

    url(r'^municipios_app/', include('municipios.urls')),
    
    url(r'^', include('cms.urls')),




)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from utils.validators import validate_CPF

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    USER_TYPE_PRINCIPAL = 0
    USER_TYPE_ASSINANTE = 1
    USER_TYPE_AVALIADOR = 2
    USER_TYPES = (
        (USER_TYPE_PRINCIPAL, "Normal"),
        (USER_TYPE_ASSINANTE, "Assinante"),
        (USER_TYPE_AVALIADOR, "Avaliador"),
    )
    user_type = models.IntegerField("Tipo", choices=USER_TYPES, null=False, default=0)
    assinante = models.IntegerField(null=True)
    cpf = models.CharField(max_length=11, validators=[validate_CPF], null=True, unique=True) #unique=True,
    empresa = models.CharField(max_length=100 , null=True)
    funcao = models.CharField("Função/Cargo", max_length=100 , null=True)
    bloqueado = models.BooleanField(default=False)
    prazo_acesso = models.DateField("Prazo de Expiração de Acesso", null=True)
    pode_finalizar_analise = models.BooleanField(u"Pode finalizar análise incompleta?", help_text= u"Caso marcado, usuário poderá finalizar análises que não estão completas.", default=False)

    def acesso_expirado(self):
        return self.prazo_acesso and self.prazo_acesso < timezone.now().date()

    def username(self):
        return self.user.username

    def first_name(self):
        return self.user.first_name

    def email(self):
        return self.user.email

    def obter_assinante(self):
        if self.user_type == Profile.USER_TYPE_ASSINANTE:
            return self.user
        elif self.user_type == Profile.USER_TYPE_AVALIADOR:
            assinante = User.objects.get(pk=self.assinante)
            return assinante
        return self.user

"""
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, "profile"):
        instance.profile.save()

"""

checklist/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now as timezone_now
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse, NoReverseMatch
from django.utils.encoding import python_2_unicode_compatible
from utils.models import CreationModificationDateMixin
from django.contrib.auth.models import User
from accounts.models import Profile
from django.db.models import Q
from utils.validators import validate_CNPJ, validate_CPF
import ast
from  municipios.fields import MunicipioForeignKey
from municipios.models import Municipio
from auditlog.registry import auditlog
from django.utils import formats
from portal import settings

#################################################################################3
# Gerenciadores SQL
##################################################################################
class AssinanteQuerySet(models.QuerySet):
    def assinante(self, user): 		
        if hasattr(user, "profile"):
        	if user.profile.user_type == Profile.USER_TYPE_ASSINANTE:
        		#return self.filter(Q(assinante = user.id) | Q(avaliador = user))
        		return self.filter(assinante = user.id)
        	else:
        		return self.filter(assinante = user.profile.assinante)					
        else:
        	return self.filter(assinante = user.id)

    def status(self, status):
        return self.filter(status__in = status)

class AvaliacaoManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)

class EmpreendimentoManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)

class AssinaturaManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)



#################################################################################3
# Classes 
##################################################################################
@python_2_unicode_compatible
class Projetista(CreationModificationDateMixin):
	"""
	"""
	cpf = models.CharField("CPF", max_length=11, validators=[validate_CPF], null=True, unique=True) 
	nome = models.CharField("Nome", max_length=200)
	crea_cau = models.CharField("CREA/CAU", max_length=200, null=True)
    #identidade = models.CharField("Identidade Funcional", max_length=100 , null=True)
	email = models.EmailField("E-mail", null=True)

	ic_ativo = models.BooleanField("Ativo", default=True)

	def __str__(self):  
    		return '%s (%s)' % (self.nome, self.cpf)

	def get_absolute_url(self):
    		return reverse('Checklists:projetista_update', kwargs={'pk': self.pk})

@python_2_unicode_compatible
class Ramo(models.Model):
	"""
		Segmentos
	Ex.: Construção civil
	"""
	nome = models.CharField(_("title"), max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descircao = models.TextField(_("descrition"), max_length=200 , blank=True, default="")
	ic_ativo = models.BooleanField(_("Ativo"), default=True)
	
	class Meta:
	   verbose_name = _("Ramo")
	   verbose_name_plural = _("Ramos")

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome

@python_2_unicode_compatible
class Plano(models.Model):
	"""
		Planos
	"""
	nome = models.CharField("Nome", max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descricao = models.TextField(u"Descrição", max_length=1000 , blank=True,  default="")
	valor = models.DecimalField("Valor (R$)", default=0.0, max_digits=6, decimal_places=2)
	dt_inicio_publicacao = models.DateField("Data de Publicação",  default=timezone_now)
	dt_fim_publicacao = models.DateField("Data Expiração", blank=True,  default=timezone_now)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	prazo = models.IntegerField(u"Fidelização", help_text=u"Quantidade de dias da vigência da assinatura", default=365)
	qtd_usuario = models.IntegerField(u"Quantidade de usuários", help_text=u"Quantidade de usuários que assinante poderá cadastrar", default=0)

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome


@python_2_unicode_compatible
class Produto(CreationModificationDateMixin):
	"""
	Classe abstrata
	"""
	class Meta:
		abstract = True

	titulo = models.CharField(u'Título', max_length=100)
	descricao = models.TextField(u"Descrição", max_length=200 , blank=True,  default="")
	planos = models.ManyToManyField(Plano)
	ramo = models.ForeignKey(Ramo, blank=True, null=True)
	folder = models.ImageField( upload_to='produtos', blank=True, verbose_name="Folder")
	dt_inicio_publicacao = models.DateField(u"Data de Publicação",  default=timezone_now)
	dt_fim_publicacao = models.DateField(u"Data Expiração", blank=True,  default=timezone_now)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	def __str__(self):  
    		return self.titulo

@python_2_unicode_compatible
class AtividadeTecnica(CreationModificationDateMixin):
	"""
	"""
	titulo = models.CharField(_("title"), max_length=100)
	descricao = models.TextField(_("description"), max_length=200 , blank=True,  default="")
	ramo = models.ForeignKey("Ramo", Ramo)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	class Meta:
		verbose_name = _("Atividade Técnica")
		verbose_name_plural = _("Atividades Técnica")

	def __str__(self):  
    		return self.titulo

@python_2_unicode_compatible
class Empreendimento(models.Model):
	"""
		Empreendimento
	"""
	objects = EmpreendimentoManager()

	nome = models.CharField("Empreendimento", max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descricao = models.TextField(u"Descrição", max_length=2000 , blank=True,  default="")
	endereco = models.TextField(u"Endereço", max_length=2000 ,  blank=True, null=True,  default="")
	municipio = MunicipioForeignKey(Municipio,  verbose_name=u'Município', help_text="Primeiramente selecione a UF e depois informe o município de localização do empreendimento.") # models.IntegerField("Município")
	assinante = models.ForeignKey(User, on_delete=models.CASCADE)


	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome

	def get_absolute_url(self):
    		return reverse('Checklists:empreendimento_update', kwargs={'pk': self.pk})

	def projetos(self):
		"""
		"""
		projetos = Projeto.objects.filter(empreendimento=self)
		return projetos

	def quantidade_projetos(self):
		"""
		Retorna a quantidade de projetos do empreendimento
		"""
		return len(self.projetos())

@python_2_unicode_compatible
class EtapaProjeto(models.Model):
	"""
		Etapa do projeto
	"""
	nome = models.CharField(_("name"), max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descircao = models.TextField(_("description"), max_length=200 , blank=True, default="")
	ic_ativo = models.BooleanField(_("Ativo"), default=True)
	

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome
	class Meta:
		verbose_name = _("Etapa do Projeto")
		verbose_name_plural = _("Etapas do Projeto")



@python_2_unicode_compatible
class Projeto(CreationModificationDateMixin):
	"""
	Atividade Técnica + Etapa do Projeto
	"""
	#slug = models.SlugField(_("slug"), max_length=40)
	#nome = models.CharField("Nome", max_length=200)
	contratante = models.CharField("Contratante", max_length=200, blank=True, null=True)
	cnpj = models.CharField("CNPJ",max_length=14, blank=True, null=True, validators=[validate_CNPJ]) #,unique=True
	contrato = models.CharField("Contrato", max_length=200, null=True,  blank=True)

	empreendimento = models.ForeignKey(Empreendimento)
	atividade_tecnica = models.ForeignKey(AtividadeTecnica, verbose_name=u'Atividade Técnica', 
			help_text=u'Atividades técnicas executadas no projeto')
	etapa_projeto = models.ForeignKey(EtapaProjeto, verbose_name=u'Etapa')

	descricao = models.TextField("Descrição", max_length=200, blank=True, default="")

	responsavel_analise = models.CharField(u'Responsável pela análise', max_length=200, default="", blank=True, null=True)
	responsavel_validacao = models.CharField(u'Responsável pela validação', blank=True, null=True, max_length=200)

	projetistas = models.ManyToManyField(Projetista, through='ProjetoProjetista')

	ic_ativo = models.BooleanField("Ativo", default=True)

	def __unicode__(self):  # Python 3: def __str__(self):
		return "%s | %s | %s" % (self.empreendimento, self.atividade_tecnica, self.etapa_projeto)

	def __str__(self):  
    		return "%s | %s | %s" % (self.empreendimento, self.atividade_tecnica, self.etapa_projeto)

	def get_absolute_url(self):
		return reverse('Checklists:projeto_update', kwargs={'pk': self.pk})


	def infoUtilizadas(self):
		infos = InformacaoProjeto.objects.filter(projeto = self).order_by('-data_revisao')
		return infos

	def obter_avaliacao(self):
		avaliacoes = Avaliacao.objects.filter(projeto = self)
		avaliacao = None
		if len(avaliacoes):
			avaliacao = avaliacoes[0]
		return avaliacao

	def checklists_disponiveis(self):
		#import pdb; pdb.set_trace()
		assinaturas = Assinatura.objects.assinante(self.empreendimento.assinante)
		if len(assinaturas):
    			assinatura = assinaturas[0]
		checklists = assinatura.plano.checklist_set.filter(atividade_tecnica=self.atividade_tecnica,
										etapa_projeto=self.etapa_projeto,

accounts/templates/accounts/change_password.html
{% load i18n staticfiles field_attrs %}

<div class="spacer spacer-xs"></div>

<div id="msg_container"></div>

<h3>Alteração de senha</h3>

<form name="form" id="form"  itens-formset-url="{% url 'accounts:change_password' %}"  
       data-url='{{ request.build_absolute_uri|safe }}'
       class="form my-ajax-form"   
       method='POST'
       enctype="multipart/form-data">


        {% csrf_token %}
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="form-group row">
            {{ field.label_tag }}
            {{ field | attr:"class=form-control"  }}
            <span class="helptext">{{ field.help_text    }}</span>
            {{ field.errors }}
        </div>
        {% endfor %}
         

        <button type="submit" class="btn btn-primary btn-xs">Salvar</button>

</form>
      

{% block javascript  %}

<script languange="javascript">

var alert_template = '<div class="alert alert-success alert-dismissible" role="alert">' +
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;' +
        '</span></button>'+ 
        '<strong>Aviso!</strong> <span>MESSSAGE</span></div>';

 $(document).ready(function(){
                var $myForm = $('.my-ajax-form');
                var url = $myForm.attr("itens-formset-url") ;
                

                
                $myForm.submit(function(event){
                        event.preventDefault()
                        var $formData = $(this).serialize()
                        var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
                        $.ajax({
                                method: "POST",
                                url: $thisURL,
                                data: $formData,
                                success: handleFormSuccess,
                                error: handleFormError,
                        })
                })
        
                function handleFormSuccess(data, textStatus, jqXHR){
                        //console.log(data)
                       // console.log(textStatus)
                       // console.log(jqXHR)

                        if(textStatus=='success'){
                                var msg = alert_template.replace("MESSSAGE", data["message"]);
                                
                                $("#msg_container").html(msg);


                                if ($("input").next('p').length) $("input").nextAll('p').empty();

                                data = data["errors"];
	                        for (var name in data) {
                                        for (var i in data[name]) {
                                                // object message error django
                                                var $input = $("input[name='"+ name +"']");
                                                $input.after("<p>" + data[name][i] + "</p>");
                                        }
                                }

                        }
                       // $myForm.reset(); // reset form data
                }
        
                function handleFormError(jqXHR, textStatus, errorThrown){
                        console.log(jqXHR);
                        console.log(textStatus);
                        console.log(errorThrown);

                        if ($("input").next('p').length) $("input").nextAll('p').empty();

                        data = jqXHR.responseJSON;

                        $.each(data, function (key, value){
                                // object message error django
                                var $input = $("input[name='"+ key +"']");
                                $input.after("<p>" + value + "</p>");
                        });
                }
        })
</script>
                


 

 <script>

  $("#id_username").parent().find("label").html("Usuário");
  $("#id_old_password").parent().find("label").html("Senha atual");
  $("#id_new_password1").parent().find("label").html("Nova senha");
  $("#id_new_password2").parent().find("label").html("Confirmação da nova senha");
 
  </script>

 


{% endblock %}

accounts/templates/accounts/logged_out.html
{% extends 'base.html' %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load i18n staticfiles field_attrs %}

{% block content %}

<div class="row">
        <div class="col-sm-8 col-sm-offset-8">
            <h3>Informe seus dados de cadastro</h3>


            <form class="form" method="post">
            {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="form-group row">
                    {{ field.label_tag }}
                    {{ field | attr:"class=form-control"  }}
                    <span class="helptext">{{ field.help_text    }}</span>
                    {{ field.errors }}
                </div>
                {% endfor %}

                
                <button type="submit" class="btn btn-primary mb-2">Entrar</button>
                
                
            <p>
                Não é cadastrado? Quer testar? <a class="link2"  href="{% url 'accounts:register' %}" title="">Cadastre-se.</a> <br />
                Esqueceu a senha? <a  class="link2" href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br />  
            </p>
            </form>
         
</div>

</div>

{% endblock %}

{% block javascript %}

 <script>
  $("#id_username").parent().find("label").html("Usuário");
  $("#id_password").parent().find("label").html("Senha");

  </script>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/profile.html
{% load render_table from django_tables2 %}

{% load i18n staticfiles field_attrs %}


<form action="" id="ajax-form-profile" method="post"  class="form" enctype="multipart/form-data"
data-url='{{ request.build_absolute_uri|safe }}'>
        {% csrf_token %}
        {{ form.non_field_errors }}

 
        {% for field in form %}
        <div class="form-group row">
                <label for="{{ field.label }}">{{ field.label}}: 
                {% if field.field.required %}<span title="Campo obrigatório" class="special_class">*</span>{% endif %}
                </label>
                <span class="helptext">{{ field.help_text    }}</span>
                {{ field | attr:"class=form-control"  }}
                {{ field.errors }}
        </div>
        {% endfor %}
        <input type="button" class="btn btn-primary btn-xs" value="Salvar" id="btnSalvarProfile"/>
        <a class="btn btn-primary btn-xs"  href="#" id="btnCancelarProfile">Cancelar</a>
   
</form>
<i class="legenda">* Campo obrigatório</i>
<br>

 

<script>

{{ form.media }}


$("input[type=checkbox]").addClass("form-check-input");
$("input[type=checkbox]").removeClass("form-control");

  $("#btnCancelarProfile").click(function (){
      listarUsuarios();

  })


        var form_profile = $('#ajax-form-profile');

        $("#btnSalvarProfile").click(function (){
       
            form_profile.submit()
            })

        form_profile.submit(function(event){
                event.preventDefault()
                var $formData = $(this).serialize()
                var $thisURL = $(this).attr('data-url') || window.location.href // or set your own url
                $.ajax({
                        method: "POST",
                        url: $thisURL,
                        data: $formData,
                        success: function (data, textStatus, jqXHR){
                                    if(textStatus=='success'){
                                        var cpf = $("#id_cpf").val();
                                        var nome = $("#id_nome").val();
                                        var data = {'value' : data.pk, 'text' : nome + " ("+ cpf+ ")" }

                                        BootstrapDialog.alert({title: 'Mensagem',   message : "Dados salvos com sucesso."});

                                        listarUsuarios();
                                    }

                            },
                        error: function (jqXHR, textStatus, errorThrown){
                                if ($("input").next('p').length) $("input").nextAll('p').empty();
                                data = jqXHR.responseJSON;
                                $.each(data, function (key, value){
                                        // object message error django
                                        var $input = $("input[name='"+ key +"']");
                                        $input.after("<p>" + value + "</p>");
                                });
                        },
                })
        })
        
        
</script>

accounts/templates/accounts/profile_form.html
{% extends "base.html" %}

{% load i18n staticfiles field_attrs %}

{% block content %}
 
<div class="row">
        <div class="col-xs-8"></div>
        <div class="col-xs-6">
                <div id="container"></div>
        </div>
 
</div>
 

{% endblock %}

{% block javascript %}

<script>

{{ form.media }}
   
        

var url = "{%url 'accounts:change_password'%}";

$("#container").html("Carregando...")
$("#container").load(url);



</script>


{% endblock %}

accounts/templates/accounts/profile_list.html
{% load render_table from django_tables2 %}

{% load i18n staticfiles field_attrs %}


{% render_table table %}