checklist/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import  url

from . import views

urlpatterns = [
    url(r'^$', views.ChecklistIndexView.as_view(), name='index'),
     url(r'^(?P<pk>\d+)/$', views.ChecklistDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ChecklistResultsView.as_view(), name='results'),
    url(r'^checklist_new$', views.ChecklistEdit.as_view(), name='checklist_new'),

    url(r'^minha_pagina$', views.MinhaPaginaView.as_view(), name='minha_pagina'),
    url(r'^minhas_aplicacoes$', views.MinhasAplicacoesView.as_view(), name='minhas_aplicacoes'),

    url(r'^avaliacao$', views.MinhasAvaliacoesView.as_view(), name='avaliacao_index'),
    url(r'^avaliacao/lista$', views.AvaliacaoListView.as_view(), name='avaliacao_list'),

    url(r'^avaliacao/criar/$', views.AvaliacaoCreateView.as_view(), name='avaliacao_add'),
    #url(r'^avaliacao/(?P<pk>\d+)/$', views.AvaliacaoItemAvaliacaoUpdateView.as_view(), name='editar_avalicao'),
    url(r'^avaliacao/(?P<pk>\d+)/$', views.editar_avaliacao, name='editar_avaliacao'),    
     url(r'^avaliacao/(?P<pk>\d+)/resultado$', views.AvaliacaoResultsView.as_view(), name='results_avaliacao'),    
     url(r'^avaliacao/(?P<pk>\d+)/pendencias$', views.AvaliacaoPendenciasView.as_view(), name='avaliacao_pendencias'), 
    url(r'^avaliacao/itens_formset$', views.obter_itens_avaliacao_formset, name='itens_avaliacao_formset'),
    url(r'^avaliacao/(?P<pk>\d+)/evolucao$', views.AvaliacaoEvolucaolView.as_view(), name='avaliacao_evolucao'),

    url(r'^avaliacao/(?P<pk>\d+)/pendencias/print$', views.RelatorioSimplificaoPrintView.as_view(), name='avaliacao_pendencias_print'), 


    url(r'empreendimento/$', views.MeusEmpreendimentosView.as_view(), name='empreendimento_index'),
    url(r'empreendimento/criar/$', views.EmpreendimentoCreate.as_view(), name='empreendimento_add'),
    url(r'empreendimento/lista/$', views.EmpreendimentoListView.as_view(), name='empreendimento_list'),
    url(r'empreendimento/(?P<pk>[0-9]+)/$',  views.EmpreendimentoUpdate.as_view(), name='empreendimento_update'),
    url(r'empreendimento/(?P<pk>[0-9]+)/delete/$',  views.EmpreendimentoDelete.as_view(), name='empreendimento_delete'),


    url(r'equipe/$', views.MinhaEquipeView.as_view(), name='minha_equipe'),

    url(r'projeto/$', views.MeusProjetosView.as_view(), name='projeto_index'),
    url(r'projeto/criar/$', views.ProjetoCreateView.as_view(), name='projeto_add'),
    url(r'projeto/criar/popup$', views.ProjetoCreatePopup.as_view(), name='projeto_add_popup'),
    url(r'projeto/lista/$', views.ProjetoListView.as_view(), name='projeto_list'),
    url(r'projeto/(?P<pk>[0-9]+)/$',  views.ProjetoUpdate.as_view(), name='projeto_update'),
    url(r'projeto/(?P<pk>[0-9]+)/delete/$',  views.ProjetoDelete.as_view(), name='projeto_delete'),


    #url(r'projeto_info/$', views.MeusProjetosView.as_view(), name='projeto_index'),
    url(r'projeto_info/criar/$', views.InformacaoProjetoCreate.as_view(), name='info_projeto_add'),
    url(r'projeto_info/lista/$', views.InformacaoProjetoListView.as_view(), name='info_projeto_list'),
    url(r'projeto_info/(?P<pk>[0-9]+)/$',  views.InformacaoProjetoUpdate.as_view(), name='info_projeto_update'),
    url(r'projeto_info/(?P<pk>[0-9]+)/delete/$',  views.InformacaoProjetoDelete.as_view(), name='info_projeto_delete'),

    url(r'projetista/criar/$', views.ProjetistaCreate.as_view(), name='projetista_add'),
    url(r'projetista/(?P<pk>[0-9]+)/$',  views.ProjetistaUpdate.as_view(), name='projetista_update'),

#chamadas ajax
    url(r'ajax/obter_checklists/$', views.obter_checklists, name='obter_checklists'),
    url(r'ajax/obter_recomendacao/$', views.obter_recomendacao, name='obter_recomendacao'),
    url(r'ajax/editar_item_avaliacao/$', views.editar_item_avaliacao, name='editar_item_avaliacao'),
    url(r'ajax/obter_estatisticas_avaliacao/$', views.obter_estatisticas_avaliacao, name='obter_estatisticas_avaliacao'),
    url(r'ajax/avaliacao_finalizar/$', views.avaliacao_finalizar, name='avaliacao_finalizar'),
    url(r'ajax/avaliacao_cancelar/$', views.avaliacao_cancelar, name='avaliacao_cancelar'),
    url(r'ajax/avaliacao_salvar_evolucao/$', views.avaliacao_salvar_evolucao, name='avaliacao_salvar_evolucao'),   


 

]

polls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
]

portal/tools/server/src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve', { 'insecure': True }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
) + i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^checklists/', include('checklist.urls', namespace='Checklists')),

    url(r'^municipios_app/', include('municipios.urls')),
    
    url(r'^', include('cms.urls')),




)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

checklist/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now as timezone_now
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse, NoReverseMatch
from django.utils.encoding import python_2_unicode_compatible
from utils.models import CreationModificationDateMixin
from django.contrib.auth.models import User
from accounts.models import Profile
from django.db.models import Q
from utils.validators import validate_CNPJ, validate_CPF
import ast
from  municipios.fields import MunicipioForeignKey
from municipios.models import Municipio
from auditlog.registry import auditlog
from django.utils import formats
from portal import settings

#################################################################################3
# Gerenciadores SQL
##################################################################################
class AssinanteQuerySet(models.QuerySet):
    def assinante(self, user): 		
        if hasattr(user, "profile"):
        	if user.profile.user_type == Profile.USER_TYPE_ASSINANTE:
        		#return self.filter(Q(assinante = user.id) | Q(avaliador = user))
        		return self.filter(assinante = user.id)
        	else:
        		return self.filter(assinante = user.profile.assinante)					
        else:
        	return self.filter(assinante = user.id)

    def status(self, status):
        return self.filter(status__in = status)

class AvaliacaoManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)

class EmpreendimentoManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)

class AssinaturaManager(models.Manager):
    def get_queryset(self):
        return AssinanteQuerySet(self.model, using=self._db)  # Important!

    def assinante(self, user):
        return self.get_queryset().assinante(user)

    def status(self, size):
        return self.get_queryset().status(size)



#################################################################################3
# Classes 
##################################################################################
@python_2_unicode_compatible
class Projetista(CreationModificationDateMixin):
	"""
	"""
	cpf = models.CharField("CPF", max_length=11, validators=[validate_CPF], null=True, unique=True) 
	nome = models.CharField("Nome", max_length=200)
	crea_cau = models.CharField("CREA/CAU", max_length=200, null=True)
    #identidade = models.CharField("Identidade Funcional", max_length=100 , null=True)
	email = models.EmailField("E-mail", null=True)

	ic_ativo = models.BooleanField("Ativo", default=True)

	def __str__(self):  
    		return '%s (%s)' % (self.nome, self.cpf)

	def get_absolute_url(self):
    		return reverse('Checklists:projetista_update', kwargs={'pk': self.pk})

@python_2_unicode_compatible
class Ramo(models.Model):
	"""
		Segmentos
	Ex.: Construção civil
	"""
	nome = models.CharField(_("title"), max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descircao = models.TextField(_("descrition"), max_length=200 , blank=True, default="")
	ic_ativo = models.BooleanField(_("Ativo"), default=True)
	
	class Meta:
	   verbose_name = _("Ramo")
	   verbose_name_plural = _("Ramos")

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome

@python_2_unicode_compatible
class Plano(models.Model):
	"""
		Planos
	"""
	nome = models.CharField("Nome", max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descricao = models.TextField(u"Descrição", max_length=1000 , blank=True,  default="")
	valor = models.DecimalField("Valor (R$)", default=0.0, max_digits=6, decimal_places=2)
	dt_inicio_publicacao = models.DateField("Data de Publicação",  default=timezone_now)
	dt_fim_publicacao = models.DateField("Data Expiração", blank=True,  default=timezone_now)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	prazo = models.IntegerField(u"Fidelização", help_text=u"Quantidade de dias da vigência da assinatura", default=365)
	qtd_usuario = models.IntegerField(u"Quantidade de usuários", help_text=u"Quantidade de usuários que assinante poderá cadastrar", default=0)

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome


@python_2_unicode_compatible
class Produto(CreationModificationDateMixin):
	"""
	Classe abstrata
	"""
	class Meta:
		abstract = True

	titulo = models.CharField(u'Título', max_length=100)
	descricao = models.TextField(u"Descrição", max_length=200 , blank=True,  default="")
	planos = models.ManyToManyField(Plano)
	ramo = models.ForeignKey(Ramo, blank=True, null=True)
	folder = models.ImageField( upload_to='produtos', blank=True, verbose_name="Folder")
	dt_inicio_publicacao = models.DateField(u"Data de Publicação",  default=timezone_now)
	dt_fim_publicacao = models.DateField(u"Data Expiração", blank=True,  default=timezone_now)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	def __str__(self):  
    		return self.titulo

@python_2_unicode_compatible
class AtividadeTecnica(CreationModificationDateMixin):
	"""
	"""
	titulo = models.CharField(_("title"), max_length=100)
	descricao = models.TextField(_("description"), max_length=200 , blank=True,  default="")
	ramo = models.ForeignKey("Ramo", Ramo)
	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	class Meta:
		verbose_name = _("Atividade Técnica")
		verbose_name_plural = _("Atividades Técnica")

	def __str__(self):  
    		return self.titulo

@python_2_unicode_compatible
class Empreendimento(models.Model):
	"""
		Empreendimento
	"""
	objects = EmpreendimentoManager()

	nome = models.CharField("Empreendimento", max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descricao = models.TextField(u"Descrição", max_length=2000 , blank=True,  default="")
	endereco = models.TextField(u"Endereço", max_length=2000 ,  blank=True, null=True,  default="")
	municipio = MunicipioForeignKey(Municipio,  verbose_name=u'Município', help_text="Primeiramente selecione a UF e depois informe o município de localização do empreendimento.") # models.IntegerField("Município")
	assinante = models.ForeignKey(User, on_delete=models.CASCADE)


	ic_ativo = models.BooleanField(_("Ativo"), default=True)

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome

	def get_absolute_url(self):
    		return reverse('Checklists:empreendimento_update', kwargs={'pk': self.pk})

	def projetos(self):
		"""
		"""
		projetos = Projeto.objects.filter(empreendimento=self)
		return projetos

	def quantidade_projetos(self):
		"""
		Retorna a quantidade de projetos do empreendimento
		"""
		return len(self.projetos())

@python_2_unicode_compatible
class EtapaProjeto(models.Model):
	"""
		Etapa do projeto
	"""
	nome = models.CharField(_("name"), max_length=200)
	#slug = models.SlugField(_("slug"), max_length=40)
	descircao = models.TextField(_("description"), max_length=200 , blank=True, default="")
	ic_ativo = models.BooleanField(_("Ativo"), default=True)
	

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.nome

	def __str__(self):  
    		return self.nome
	class Meta:
		verbose_name = _("Etapa do Projeto")
		verbose_name_plural = _("Etapas do Projeto")



@python_2_unicode_compatible
class Projeto(CreationModificationDateMixin):
	"""
	Atividade Técnica + Etapa do Projeto
	"""
	#slug = models.SlugField(_("slug"), max_length=40)
	#nome = models.CharField("Nome", max_length=200)
	contratante = models.CharField("Contratante", max_length=200, blank=True, null=True)
	cnpj = models.CharField("CNPJ",max_length=14, blank=True, null=True, validators=[validate_CNPJ]) #,unique=True
	contrato = models.CharField("Contrato", max_length=200, null=True,  blank=True)

	empreendimento = models.ForeignKey(Empreendimento)
	atividade_tecnica = models.ForeignKey(AtividadeTecnica, verbose_name=u'Atividade Técnica', 
			help_text=u'Atividades técnicas executadas no projeto')
	etapa_projeto = models.ForeignKey(EtapaProjeto, verbose_name=u'Etapa')

	descricao = models.TextField("Descrição", max_length=200, blank=True, default="")

	responsavel_analise = models.CharField(u'Responsável pela análise', max_length=200, default="", blank=True, null=True)
	responsavel_validacao = models.CharField(u'Responsável pela validação', blank=True, null=True, max_length=200)

	projetistas = models.ManyToManyField(Projetista, through='ProjetoProjetista')

	ic_ativo = models.BooleanField("Ativo", default=True)

	def __unicode__(self):  # Python 3: def __str__(self):
		return "%s | %s | %s" % (self.empreendimento, self.atividade_tecnica, self.etapa_projeto)

	def __str__(self):  
    		return "%s | %s | %s" % (self.empreendimento, self.atividade_tecnica, self.etapa_projeto)

	def get_absolute_url(self):
		return reverse('Checklists:projeto_update', kwargs={'pk': self.pk})


	def infoUtilizadas(self):
		infos = InformacaoProjeto.objects.filter(projeto = self).order_by('-data_revisao')
		return infos

	def obter_avaliacao(self):
		avaliacoes = Avaliacao.objects.filter(projeto = self)
		avaliacao = None
		if len(avaliacoes):
			avaliacao = avaliacoes[0]
		return avaliacao

	def checklists_disponiveis(self):
		#import pdb; pdb.set_trace()
		assinaturas = Assinatura.objects.assinante(self.empreendimento.assinante)
		if len(assinaturas):
    			assinatura = assinaturas[0]
		checklists = assinatura.plano.checklist_set.filter(atividade_tecnica=self.atividade_tecnica,
										etapa_projeto=self.etapa_projeto,

polls/models.py
#-*- coding: utf-8 -*-
from django.db import models


class Poll(models.Model):
    question = models.CharField(max_length=200)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text

checklist/templates/checklist/avaliacao_form.html
{% load i18n staticfiles field_attrs %}
 
{% block checklist_content %}


<form action="" method="POST"  class="form" id="ajax-form"
enctype="multipart/form-data"
data-url='{{ request.build_absolute_uri|safe }}'
data-checklists-url="{% url 'Checklists:obter_checklists' %}">

        {% csrf_token %}
         
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="form-group row">
                <label for="{{ field.label }}">{{ field.label}}: 
                {% if field.field.required %}<span title="Campo obrigatório" class="special_class">*</span>{% endif %}
                </label>
                <span class="helptext">{{ field.help_text    }}</span>
                {{ field | attr:"class=form-control"  }}
                {{ field.errors }}
        </div>
        {% endfor %}

         

        <input type="submit" class="btn btn-primary btn-xs" value="Salvar" />
        <a class="btn btn-primary btn-xs" id="btnCancelar" >Voltar</a>
        
      
</form>
<i class="legenda">* Campo obrigatório</i>
<br>
{% endblock %}


{% block javascript  %} 
<script>
        var form = $('#ajax-form');
 

        //registar eventos

        $("#btnCancelar").click(function (){
                
                carregarAplicacoes();
        });

      $("#id_projeto").change(function () {
        var url = form.attr("data-checklists-url");  // get the url of the `load_checklists` view
        var projetoId = $(this).val();  // get the selected country ID from the HTML input

        var $input = $("#id_checklist");
        $input.html("<option value=''>---------</option>");
        $input.parent().find("p").remove();

                $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                        data: {
                        'projeto': projetoId       // add the country id to the GET parameters
                        },
                        success: function (response) {   // `data` is the return of the `load_cities` view function
                                data = response.data;
                                options = "";
                                key = 0;
                                if (data.length > 0){
                                        $.each(data, function (i, item){
                                                key =  item.key;
                                        options += "<option value='" + item.key + "'>" + item.value + "</option>";
                                        })
                                        $input.html(options);  // replace the contents of the city input with the data that came from the server
                                        $input.val(key);
                                }else{
                                        var msg = "Não há lista de verificação disponível para esse projeto (Atividade técnica/Etapa)."
                                        
                                        $input.after("<p alert>" + msg + "</p>");
                                        BootstrapDialog.alert(msg );
                                }
                        }
                });
      });


      //form sumit


        form.submit(function(event){
                event.preventDefault()
                var $formData = $(this).serialize()
                var $thisURL = form.attr('data-url') || window.location.href // or set your own url
                $.ajax({
                        method: "POST",
                        url: $thisURL,
                        data: $formData,
                        success: handleFormSuccess,
                        error: handleFormError,
                })
        })
        
        function handleFormSuccess(data, textStatus, jqXHR){

                if(textStatus=='success'){

                         
                        // carregarAplicacoes();
                         var url = data["success_url"];
                        $("#container").html("Carregando...")
                        $("#container").load(url);
                }

        }

        function handleFormError(jqXHR, textStatus, errorThrown){
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
                console.log(jqXHR.responseText)

                if ($("input").next('p').length) $("input").nextAll('p').empty();

                data = jqXHR.responseJSON;


                var msg = "";

                $.each(data, function (key, value){
                        // object message error django
                        if (key == "__all__") 
                                msg += value;
                        else {
                                var $input = $("input[name='"+ key +"']");
                                $input.after("<p>" + value + "</p>");

                        }
                });

                if (msg != ""){
                        var $input = $("#id_checklist");
                        $input.parent().find("p").remove();
                        $input.after("<p alert>" + msg + "</p>");
                        BootstrapDialog.alert(msg );
                }


        }
    
     //   $("#id_projeto").after("<button title='Novo projeto'  class='btn btn-primary pull-right btn-sm RbtnMargin' type='button'><i class='fa fa-plus'></i></button>");
     var url_new = "{%url 'Checklists:projeto_add_popup'%}";
     $("#id_projeto").parent().find("label").append(  '&nbsp;&nbsp;<a class="related-widget-wrapper-link add-related" id="add_id_projeto" href='+ url_new+'?_to_field=id_projeto&amp;_popup=1" title="Adicionar outro projeto"><img src="/static/admin/img/icon-addlink.svg" alt="Adicionar"></a>');
     

  

     $("#add_id_projeto").click(function (){
        var url = $(this).attr("href");  
           BootstrapDialog.show({
                   title: "Novo projeto",
                   message: $('<div></div>').load(url)
            });
             return false;

     })

 </script>       

 


{% endblock %}

checklist/templates/checklist/base.html
{% extends 'base.html' %}


{% block content %}

    {% block checklist_content %}
    {% endblock %}

{% endblock %}

checklist/templates/checklist/detail.html
{% extends 'checklist/base.html' %}

{% block checklist_content %}
<h1>{{ checklist.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'Checklists:results' checklist.id %}" method="post">
{% csrf_token %}
{% for choice in checklist.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

checklist/templates/checklist/minha_pagina.html
{% extends 'base.html' %}
{% load i18n staticfiles cms_tags %}


{% block content %}
    
<ul class="nav nav-tabs nav-justified">
{%if abas %}
    {%for aba in abas %}
       {% if aba.title == aba_default %}
                <li role="presentation" class="active"><a data-toggle="tab" href="#{{aba.title}}">{{aba.title}}</a></li>
        {%else%}
                <li role="presentation" ><a data-toggle="tab" href="#{{aba.title}}">{{aba.title}}</a></li>
        {%endif%}
    {%endfor%}
{%endif%}
</ul>

<div id="container">Carregando...</div>


{% endblock %}


{% block javascript %}


        <script>

           function carregarAplicacoes(){
                                var url = "{%url 'Checklists:minhas_aplicacoes'%}";

                                $("#container").html("Carregando...")
                                $("#container").load(url);
           }

                $(document).ready(function(){

                        activaTab("{{aba_default}}");

                        $('.nav-tabs a').click(function (e) {
                                var tab = $(e.target).text();         // active tab
                                activaTab(tab);
                        });

                        $('.nav-tabs a').on('shown.bs.tab', function(event){
                                var tab = $(event.target).text();         // active tab
                                var y = $(event.relatedTarget).text();  // previous tab
                                // activaTab(tab);
                                
                        }); 
                });
                
                function activaTab(tab){
                        switch(tab) {
                        case "Empreendimentos":
                                var url = "{%url 'Checklists:empreendimento_index'%}";

                                $("#container").html("Carregando...")
                                $("#container").load(url);

                                break;
                        case "Projetos":
                                var url = "{%url 'Checklists:projeto_index'%}";

                                $("#container").html("Carregando...")
                                $("#container").load(url);

                                break;
                        case "Aplicações":
                                carregarAplicacoes();

                                break;
                        case "Equipe":
                                var url = "{%url 'Checklists:minha_equipe'%}";

                                $("#container").html("Carregando...")
                                $("#container").load(url);
                                break;
                        case "Conta":
                                var url = "{%url 'accounts:change_password'%}";

                                $("#container").html("Carregando...")
                                $("#container").load(url);
                                break;
                        default:
                                $("#container").html("Em desenvolvimento...")
                        } 
 
                };
        </script>


{% endblock %}

 

checklist/templates/checklist/minhas_avaliacoes.html
{% load render_table from django_tables2 %}

{% block checklist_content %}

 
<form id="filter_form">

        <a class="btn btn-primary btn-xs"  href="#" id="btnNovo"><i class="fa fa-plus"></i> Criar nova análise</a>
        <label class="checkbox-inline"><input name="status" checked type="checkbox" class="checkbox" value="0">A realizar</label>
        <label class="checkbox-inline"><input name="status" checked type="checkbox" class="checkbox" value="1">Em andamento</label>
        <label class="checkbox-inline"><input name="status" checked type="checkbox" class="checkbox"  value="2">Finalizada</label>
        <label class="checkbox-inline"><input name="status"  type="checkbox" class="checkbox"  value="3">Cancelada</label>

</form>
<div class="spacer spacer-xs"></div>

<div id="avaliacoes_list"></div>


{% endblock %}



{% block javascript %}

 <script>

        function editarAnalise(obj){

                $( "#filter_form" ).hide();
                var url = $(obj).attr("href");
                $("#container").html("Carregando...")
                $("#container").load(url);
                return false;

        }

        function visualizarRelatorio(obj){

                $( "#filter_form" ).hide();
                var url = $(obj).attr("href");
                $("#container").html("Carregando...")
                $("#container").load(url);
                return false;

        }
        function filtrarLista(){

                $( "select" ).prop( "disabled", false );
                $( "textarea" ).prop( "disabled", false );
                $( "input" ).prop( "disabled", false );


                $( "#filter_form" ).show();
                var url = "{%url 'Checklists:avaliacao_list'%}";
                var param =  $( "#filter_form" ).serialize();

                $("#avaliacoes_list").html("Carregando...")
                $("#avaliacoes_list").load(url + "?" + param);
        }

        $(".checkbox").change(function (){
                 filtrarLista();
        })

        $("#btnNovo").click(function (){
                $( "#filter_form" ).hide();
                var url = "{% url 'Checklists:avaliacao_add' %}"
                $("#container").html("Carregando...")
                $("#container").load(url);
        });

        filtrarLista();
 </script>

{% endblock %}